### ISSUE TITLE
prettier 포맷 공통 설정 적용

### ISSUE THREAD

**Issue by chb09876** [AI-Funding/AI_Funding_FE#32]
포맷이 통일되지 않다보니 쓸데없는 변경이 발생할 수 있습니다. (따옴표가 쌍따옴표로 바뀐다든가 탭이 스페이스 4개에서 2개로 바뀐다든가...)
그래서 공통적인 포맷 규칙을 적용하고 싶습니다.

다들 vscode사용하시니깐 .prettierrc파일을 프로젝트에 넣으면 적힌 내용에 따라서 포맷설정이 적용됩니다.
아래 내용들에 대해 설정을 할 예정인데 어떤게 좋을지 생각해주시고 추가할 내용 있으면 알려주세영

- indent: tab? 4-space? 2-space?
- 'single quote'? "double quote"?
- arrow function 형태
```javascript
// case 1
const case1 = (obj) => ("any return value");

// case 2
const case2 = (obj) => "any return value";

// case 3
const case1 = obj => ("any return value");

// case 4
const case4 = obj => "any return value";
```
- if문 블록 형태
```javascript
// case 1
if(true){
  console.log("case1");
} else {
  console.log("case1");
}

// case 2
if(true)
  console.log("case2");
else 
  console.log("case2");

// case 3
if(true) console.log("case3");
else console.log("case3");
```

**Comment by HoSeong0731** [comment]
첨언하자면 1Tab은 2space냐 4space냐는 꽤 오래전부터 있었던 논쟁거리입니다!
그러나 대부분의 툴에서 4space가 Default로 되어있기 때문에 4space로 가는 게 좋을 것 같아요 :) 
https://dev.to/wolfhoundjesse/4-spaces-or-2-3423

다른 것들은 FE 분들끼리 논의하시면 좋을 것 같습니다 :)
해당 이슈는 협업하는데에 있어 좋은 이슈인 것 같네요.
포맷을 통일하면 코드리뷰 중 불필요한 변경사항들이 줄가 때문에 확인하기 더 쉬울 것 같습니다.

추가로 javascript if else vs switch performance에 대해서도 얘기 나눌 수 있으면 좋을 것 같습니다!

@kwYoohae BE 쪽은 1Tab = 4Space쪽으로 진행되도록 가이드 해주세요! 
(툴에서 기본 값을 변경하지 않았으면 모두 동일할 겁니다.)
+ Java if else vs switch performance에 대해 알아보는 것도 좋을 것 같아요 :)

**Comment by kwYoohae** [comment]
@HoSeong0731 IDE에서 알아서 해줘서 딱히 상관없는 것 같습니다

`if else` 부분에 대해서는 case 정리해 두는거 생각해 보도록 하겠습니다.

**Comment by mouse0429** [comment]
1. 탭 간격은 개인적으로 2 space를 선호하지만 협업에선 호성님께서 말씀하신대로 기본값을 따르는게 맞는 것같습니다. 4 space 동의합니다.
2. if 블록에서 한 줄만 있을 때 중괄호를 생략하는 문제도 추가하면 좋을 것 같습니다 (개인적으로 수정이나 추가할 때 중괄호를 생략하지 않는 편이 더 낫다고 생각해서 생략하지 않는 것을 선호합니다.)
3. 나머지는 오늘 회의에서 의견 드리도록 하겠습니다.
